HSNR = HSNR or {}

HSNR.MESSAGE = {}
HSNR.MESSAGE.NO_QUEUE = 0x01
HSNR.MESSAGE.NAIL_REMOVED = 0x02
HSNR.MESSAGE.SHOWLIST = 0x04
HSNR.MESSAGE.WRONG_ARGUMENT = 0x08
HSNR.MESSAGE.TARGET_DISCONNECT = 0x10
HSNR.MESSAGE.PENALTY_POINT = 0x20
HSNR.MESSAGE.PENALTY_BRAIN = 0x40
HSNR.MESSAGE.PENALTY_DAMAGE = 0x80
HSNR.MESSAGE.PENALTY_KICK = 0x100
HSNR.MESSAGE.PROCESS_PENALTY_POINT = 0x200
HSNR.MESSAGE.PROCESS_PENALTY_BRAIN = 0x400
HSNR.MESSAGE.PROCESS_PENALTY_DAMAGE = 0x800
HSNR.MESSAGE.PROCESS_PENALTY_KICK = 0x1000